# Generated by Django 4.2.5 on 2023-09-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mailing_clients',
            field=models.ManyToManyField(to='agent.client', verbose_name='подписчики'),
        ),
    ]
