# Generated by Django 4.2.5 on 2023-09-11 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_alter_client_client_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('set_mailing_status', 'Can change the status of mailing')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
