# Generated by Django 4.2.5 on 2023-09-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_alter_mailing_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='почта'),
        ),
    ]
